services:
  backend:
    build:
      context: ./bdproj
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "9000:8000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: ./lms_front
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
        image: postgres:16.1
        container_name: db
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: adaptivesystem
        ports:
            - 5432:5432
volumes:
    postgres_data:
